package erp

import (
	"encoding/json"
	"fmt"
	"net/http/httptest"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// TestGenerateAdapterMapping writes the per-field mapping matrix used in
// docs/starterp/ADAPTER_MAPPING.md. It is EMPIRICAL: for every contract
// field it mutates the field on a record read from a real legacy document and
// diffs the legacy payload the adapter would send to the v1 handler, so the
// matrix is always what the code does. Opt-in:
//
//	ERP_TEST_DB=1 ERP_GEN_MAPPING=/tmp/matrix.md ERP_CONTRACT_JSON=…/contract.json go test ./erp/ -run TestGenerateAdapterMapping -count=1
func TestGenerateAdapterMapping(t *testing.T) {
	out, cpath := os.Getenv("ERP_GEN_MAPPING"), os.Getenv("ERP_CONTRACT_JSON")
	if out == "" || cpath == "" {
		checkAdapterMappingDoc(t)
		return
	}
	requireDB(t)
	raw, err := os.ReadFile(cpath)
	if err != nil {
		t.Fatal(err)
	}
	var contract mappingContract
	if err := json.Unmarshal(raw, &contract); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(out, []byte(generateMapping(t, contract)), 0o644); err != nil {
		t.Fatal(err)
	}
}

type mappingContract struct {
	Resources []struct {
		Name   string                 `json:"name"`
		Path   string                 `json:"path"`
		Fields map[string]interface{} `json:"fields"`
	} `json:"resources"`
}

func generateMapping(t *testing.T, contract mappingContract) string {
	t.Helper()
	tok := login(t, fx.AdminEmail)
	req := httptest.NewRequest("GET", "/", nil)
	req.Header.Set("Authorization", "Bearer "+tok)
	c, err := authenticate(req)
	if err != nil {
		t.Fatal(err)
	}
	var b strings.Builder
	totals := map[string]int{}
	for _, cr := range contract.Resources {
		path := strings.TrimPrefix(cr.Path, "/v1/")
		res := resourceByPath(path)
		if res == nil {
			fmt.Fprintf(&b, "\n### %s (`/%s`) — NOT MOUNTED\n", cr.Name, path)
			continue
		}
		rows, kind := mapResource(t, c, res, cr.Fields)
		for _, r := range rows {
			totals[r.class]++
		}
		fmt.Fprintf(&b, "\n### %s — `/v1/erp/%s`\n\n%s\n\n", cr.Name, path, kind)
		b.WriteString("| Contract field | Type | Mapping | Class |\n|---|---|---|---|\n")
		for _, r := range rows {
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", r.path, r.typ, r.mapping, r.class)
		}
	}
	var sum []string
	for k, v := range totals {
		sum = append(sum, fmt.Sprintf("%s: %d", k, v))
	}
	sort.Strings(sum)
	head := "<!-- generated by TestGenerateAdapterMapping; do not edit by hand -->\nField totals — " + strings.Join(sum, " · ") + "\n"
	return strings.ReplaceAll(head+b.String(), storeA(), "<storeId>")
}

// resolved at package init, before TestMain moves the cwd to a temp dir
var mappingDocPath, _ = filepath.Abs("../docs/starterp/ADAPTER_MAPPING.md")

var reMatrixRow = regexp.MustCompile("^\\| `([^`]+)` \\| ([^|]+) \\| .* \\| ([a-z]+) \\|$")
var reMatrixRes = regexp.MustCompile("^### (.+) — `/v1/erp/([^`]+)`$")

// parseMappingDoc reads the generated matrix of docs/starterp/ADAPTER_MAPPING.md
// into resource path -> field -> class, plus a contract rebuilt from it.
func parseMappingDoc(t *testing.T) (map[string]map[string]string, mappingContract) {
	t.Helper()
	raw, err := os.ReadFile(mappingDocPath)
	if err != nil {
		t.Fatal(err)
	}
	text := string(raw)
	i := strings.Index(text, "<!-- generated by TestGenerateAdapterMapping")
	if i < 0 {
		t.Fatal("ADAPTER_MAPPING.md has no generated matrix")
	}
	classes := map[string]map[string]string{}
	var contract mappingContract
	var cur map[string]interface{}
	var curPath string
	for _, line := range strings.Split(text[i:], "\n") {
		if m := reMatrixRes.FindStringSubmatch(line); m != nil {
			curPath = m[2]
			cur = map[string]interface{}{}
			classes[curPath] = map[string]string{}
			contract.Resources = append(contract.Resources, struct {
				Name   string                 `json:"name"`
				Path   string                 `json:"path"`
				Fields map[string]interface{} `json:"fields"`
			}{m[1], "/v1/" + curPath, cur})
			continue
		}
		m := reMatrixRow.FindStringSubmatch(line)
		if m == nil || cur == nil {
			continue
		}
		classes[curPath][m[1]] = m[3]
		addSpecPath(cur, m[1], strings.TrimSpace(m[2]))
		if e := mappingEnumHints[curPath+"."+m[1]]; e != nil {
			cur[m[1]].(map[string]interface{})["enum"] = e
		}
	}
	return classes, contract
}

// mappingEnumHints restores contract enums the doc's Type column does not
// show, for fields whose probe value must be one of them.
var mappingEnumHints = map[string][]interface{}{
	"employees.status": {"active", "inactive"},
}

// addSpecPath adds "a.b[].c" with type typ to a contract fields map.
func addSpecPath(fields map[string]interface{}, path, typ string) {
	parts := strings.SplitN(path, ".", 2)
	key := parts[0]
	if len(parts) == 1 {
		fields[key] = map[string]interface{}{"type": typ}
		return
	}
	isArr := strings.HasSuffix(key, "[]")
	key = strings.TrimSuffix(key, "[]")
	sp, _ := fields[key].(map[string]interface{})
	if sp == nil {
		sp = map[string]interface{}{}
		fields[key] = sp
	}
	var sub map[string]interface{}
	if isArr {
		sp["type"] = "array"
		it, _ := sp["items"].(map[string]interface{})
		if it == nil {
			it = map[string]interface{}{"type": "object", "fields": map[string]interface{}{}}
			sp["items"] = it
		}
		sub = it["fields"].(map[string]interface{})
	} else {
		sp["type"] = "object"
		if sp["fields"] == nil {
			sp["fields"] = map[string]interface{}{}
		}
		sub = sp["fields"].(map[string]interface{})
	}
	addSpecPath(sub, parts[1], typ)
}

// checkAdapterMappingDoc regenerates the matrix from the contract fields the
// doc lists and fails when a field's class (mapped/new/computed/server)
// no longer matches what the code does, so the doc cannot silently drift.
func checkAdapterMappingDoc(t *testing.T) {
	requireDB(t)
	want, contract := parseMappingDoc(t)
	if len(contract.Resources) < 40 {
		t.Fatalf("parsed only %d resources from ADAPTER_MAPPING.md", len(contract.Resources))
	}
	got := map[string]map[string]string{}
	var curPath string
	for _, line := range strings.Split(generateMapping(t, contract), "\n") {
		if m := reMatrixRes.FindStringSubmatch(line); m != nil {
			curPath = m[2]
			got[curPath] = map[string]string{}
			continue
		}
		if m := reMatrixRow.FindStringSubmatch(line); m != nil && curPath != "" {
			got[curPath][m[1]] = m[3]
		}
	}
	var drift []string
	for res, fields := range want {
		for f, cls := range fields {
			if g := got[res][f]; g != cls {
				drift = append(drift, fmt.Sprintf("%s.%s: doc says %q, code gives %q", res, f, cls, g))
			}
		}
	}
	sort.Strings(drift)
	if len(drift) > 0 {
		t.Errorf("ADAPTER_MAPPING.md drifted from the adapter (%d fields); regenerate it:\n%s", len(drift), strings.Join(drift, "\n"))
	}
}

type mapRow struct{ path, typ, mapping, class string }

type fieldSpec struct {
	path string
	typ  string
	enum []string
}

func walkSpec(fields map[string]interface{}, prefix string, out *[]fieldSpec) {
	keys := make([]string, 0, len(fields))
	for k := range fields {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	seen := map[string]bool{}
	for _, k := range keys {
		sp, _ := fields[k].(map[string]interface{})
		typ := str(sp["type"])
		if reSeedWH.MatchString(k) { // product stock map keyed by warehouse id
			k = "<warehouseId>"
		}
		p := prefix + k
		if seen[p] {
			continue
		}
		seen[p] = true
		var enum []string
		for _, e := range arr(sp["enum"]) {
			enum = append(enum, str(e))
		}
		if sub, ok := sp["fields"].(map[string]interface{}); ok && len(sub) > 0 {
			walkSpec(sub, p+".", out)
			continue
		}
		if it, ok := sp["items"].(map[string]interface{}); ok {
			if sub, ok := it["fields"].(map[string]interface{}); ok && len(sub) > 0 {
				walkSpec(sub, p+"[].", out)
				continue
			}
		}
		*out = append(*out, fieldSpec{p, typ, enum})
	}
}

func unwrapLegacy(be Backend) (*legacyBackend, *nativeBackend, string) {
	switch v := be.(type) {
	case *legacyBackend:
		return v, nil, ""
	case *storesBackend:
		return v.legacyBackend, nil, ""
	case *usersBackend:
		return v.legacyBackend, nil, ""
	case *warehousesBackend:
		return v.legacyBackend, nil, "plus a virtual read-only warehouse `ms_<storeId>` = the legacy `main_store` stock bucket (warehouse_id null)"
	case *stockTransfersBackend:
		return v.legacy, nil, "status `pending` transfers live in `" + v.pending.coll + "` (no legacy equivalent: legacy transfers move stock immediately); completing one creates the legacy `stocktransfer` (new id, `replacedId` = pending id)"
	case *rolesBackend:
		return nil, v.custom, "system roles are built in (read-only); legacy `user_role` documents are listed read-only; custom roles are stored in `" + v.custom.coll + "` (main DB)"
	case *nativeBackend:
		return nil, v, ""
	}
	return nil, nil, ""
}

// sampleDoc returns a real legacy document for the resource: a fixture
// document when one exists, otherwise one created through the adapter.
func sampleDoc(t *testing.T, c *Ctx, res *Resource, lb *legacyBackend) (string, M) {
	fixtureIDs := map[string]string{"stores": storeA(), "users": fx.ManagerA.Hex(), "sales": fx.OrderA1.Hex(), "sales-returns": fx.SalesReturnA1.Hex(),
		"quotations": fx.QuotationA1.Hex(), "purchases": fx.PurchaseA1.Hex(), "expenses": fx.ExpenseA1.Hex(), "deposits": fx.DepositA1.Hex(),
		"withdrawals": fx.WithdrawalA1.Hex(), "capitals": fx.CapitalA1.Hex(), "dividends": fx.DividentA1.Hex(), "salaries": fx.SalaryA1.Hex(),
		"employees": fx.EmployeeA1.Hex(), "vehicles": fx.VehicleA1.Hex(), "repair-jobs": fx.RepairJobA1.Hex(), "stock-transfers": fx.TransferA1.Hex(),
		"delivery-notes": fx.DeliveryNoteA1.Hex(), "accounts": fx.AccountA1.Hex(), "packages": fx.PackageA1.Hex(), "products": fx.ProductA1.Hex(),
		"customers": fx.CustomerA1.Hex(), "vendors": fx.VendorA1.Hex(), "categories": fx.CategoryA.Hex(), "brands": fx.BrandA.Hex(),
		"expense-categories": fx.ExpenseCatA.Hex(), "vendor-categories": fx.VendCat.Hex(), "warehouses": fx.WarehouseA.Hex()}
	id := fixtureIDs[res.Path]
	if id == "" {
		var body M
		for _, rc := range resourceCases() {
			if rc.path == res.Path {
				body = rc.body()
			}
		}
		ms := "ms_" + storeA()
		switch res.Path {
		case "purchase-returns":
			body = M{"storeId": storeA(), "date": "2026-10-05T10:00", "purchaseId": fx.PurchaseA1.Hex(), "vendorId": fx.VendorA1.Hex(),
				"items": []M{{"productId": fx.ProductA1.Hex(), "qty": 1, "unitPrice": 80, "warehouseId": ms, "vatPercent": 15}}}
		case "quotation-returns":
			tok := login(t, fx.AdminEmail)
			q := call(t, "POST", "/quotations", tok, M{"storeId": storeA(), "date": "2026-10-05T10:00", "customerId": fx.CustomerA1.Hex(), "type": "invoice",
				"status": "created", "validityDays": 7, "deliveryDays": 3,
				"items": []M{{"productId": fx.ProductA2.Hex(), "qty": 2, "unitPrice": 25, "warehouseId": ms, "vatPercent": 15}}})
			body = M{"storeId": storeA(), "date": "2026-10-05T10:00", "quotationId": str(q.Body["id"]), "customerId": fx.CustomerA1.Hex(),
				"items": []M{{"productId": fx.ProductA2.Hex(), "qty": 1, "unitPrice": 25, "warehouseId": ms, "vatPercent": 15}}}
		case "nonvat-returns":
			tok := login(t, fx.AdminEmail)
			ns := call(t, "POST", "/nonvat-sales", tok, M{"storeId": storeA(), "date": "2026-10-05T10:00", "customerId": fx.CustomerA1.Hex(),
				"items": []M{{"productId": fx.ProductA2.Hex(), "qty": 2, "unitPrice": 30, "warehouseId": ms, "vatPercent": 0}}})
			body = M{"storeId": storeA(), "date": "2026-10-05T10:00", "orderId": str(ns.Body["id"]), "customerId": fx.CustomerA1.Hex(),
				"items": []M{{"productId": fx.ProductA2.Hex(), "qty": 1, "unitPrice": 30, "warehouseId": ms, "vatPercent": 0}}}
		}
		if body == nil {
			return "", nil
		}
		r := call(t, "POST", "/"+res.Path, login(t, fx.AdminEmail), body)
		if r.Code != 201 {
			t.Logf("sample %s: %d %s", res.Path, r.Code, truncate(r.Raw, 300))
			return "", nil
		}
		id = str(r.Body["id"])
	}
	sh := storeA()
	if res.Scope == "org" && !lb.mainOrg && !lb.inMain {
		sh = storeA()
	}
	d, err := lb.loadRaw(c, sh, id, true)
	if err != nil || d == nil {
		t.Logf("load sample %s/%s: %v", res.Path, id, err)
		return "", nil
	}
	return sh, d
}

var reSeedWH = regexp.MustCompile(`^st_[a-z]+_wh\d+$`)

// concrete returns the probe path for a matrix path.
func concrete(p string) string { return strings.ReplaceAll(p, "<warehouseId>", "ms_"+storeA()) }

var reDT = regexp.MustCompile(`^\d{4}-\d\d-\d\dT\d\d:\d\d$`)
var reDay = regexp.MustCompile(`^\d{4}-\d\d-\d\d$`)

func refCandidates(key string) []string {
	k := strings.ToLower(key)
	switch {
	case strings.Contains(k, "customer"):
		return []string{fx.CustomerA2.Hex(), fx.CustomerA1.Hex()}
	case strings.Contains(k, "vendor"):
		return []string{fx.VendorA1.Hex()}
	case strings.Contains(k, "product"):
		return []string{fx.ProductA3.Hex(), fx.ProductA2.Hex()}
	case strings.Contains(k, "warehouse"):
		return []string{fx.WarehouseA.Hex(), "ms_" + storeA()}
	case strings.Contains(k, "employee"):
		return []string{fx.EmployeeA1.Hex()}
	case strings.Contains(k, "vehicle"):
		return []string{fx.VehicleA1.Hex()}
	case strings.Contains(k, "categor"):
		return []string{fx.ExpenseCatA.Hex(), fx.CategoryA.Hex(), fx.VendCat.Hex()}
	case strings.Contains(k, "brand"):
		return []string{fx.BrandA.Hex()}
	case strings.Contains(k, "order"):
		return []string{fx.OrderA2.Hex(), fx.OrderA1.Hex()}
	case strings.Contains(k, "purchase"):
		return []string{fx.PurchaseA1.Hex()}
	case strings.Contains(k, "quotation"):
		return []string{fx.QuotationA1.Hex()}
	case strings.Contains(k, "store"):
		return []string{storeB(), storeA()}
	case strings.Contains(k, "repairjob"):
		return []string{fx.RepairJobA1.Hex()}
	}
	return []string{fx.CustomerA2.Hex()}
}

// pickOther returns a, or b when the field already holds a (an earlier test
// may have left the probe value behind, which would hide the mapping).
func pickOther(cur, a, b string) string {
	if cur == a {
		return b
	}
	return a
}

func probeValue(fs fieldSpec, cur interface{}) (interface{}, bool) {
	last := fs.path[strings.LastIndex(fs.path, ".")+1:]
	last = strings.TrimSuffix(last, "[]")
	if len(fs.enum) > 0 {
		for _, e := range fs.enum {
			if e != str(cur) {
				return e, true
			}
		}
	}
	switch v := cur.(type) {
	case bool:
		return !v, true
	case float64:
		return v + 1, true
	case int64:
		return float64(v) + 1, true
	case []interface{}:
		if strings.HasSuffix(last, "Ids") {
			return append(append([]interface{}{}, v...), refCandidates(last)[0]), true
		}
		return append(append([]interface{}{}, v...), "probe"), true
	case M:
		return nil, false
	}
	s := str(cur)
	switch {
	case strings.Contains(fs.typ, "datetime") || reDT.MatchString(s):
		return "2025-03-04T05:06", true
	case reDay.MatchString(s) || strings.HasSuffix(last, "Date") && !strings.Contains(fs.typ, "number"):
		return "2025-03-04", true
	case strings.HasSuffix(last, "Id") && last != "keyId" && last != "pcsid":
		for _, cnd := range refCandidates(last) {
			if cnd != s {
				return cnd, true
			}
		}
		return nil, false
	case strings.Contains(fs.typ, "number") || strings.Contains(fs.typ, "integer"):
		return num(cur) + 1, true
	case fs.typ == "boolean":
		return !boolv(cur), true
	case strings.Contains(strings.ToLower(last), "phone") || strings.HasPrefix(last, "mob"):
		return pickOther(s, "0551112223", "0551112224"), true
	case strings.Contains(strings.ToLower(last), "email"):
		return pickOther(s, "probe@t1.example", "probe2@t1.example"), true
	case last == "vatNo":
		return pickOther(s, "399999999900003", "399999999800003"), true
	case last == "crNo":
		return pickOther(s, "2020202020", "2020202021"), true
	case strings.HasPrefix(fs.typ, "array"):
		return []interface{}{"probe"}, true
	}
	if s == "" {
		return "Probe", true
	}
	return s + "Z", true
}

// setPath sets a dotted path ("items[].qty" → first element) on a deep copy.
func setPath(m M, path string, v interface{}) bool {
	parts := strings.Split(path, ".")
	cur := m
	for i, p := range parts {
		isArr := strings.HasSuffix(p, "[]")
		key := strings.TrimSuffix(p, "[]")
		if i == len(parts)-1 && !isArr {
			cur[key] = v
			return true
		}
		if isArr {
			a := arr(cur[key])
			if len(a) == 0 {
				return false
			}
			el := normDoc(a[0])
			na := append([]interface{}{el}, a[1:]...)
			cur[key] = na
			if i == len(parts)-1 {
				return false
			}
			cur = el
			continue
		}
		nx := normDoc(cur[key])
		cur[key] = nx
		cur = nx
	}
	return false
}

func getPath(m M, path string) interface{} {
	parts := strings.Split(path, ".")
	var cur interface{} = m
	for _, p := range parts {
		mm, ok := cur.(M)
		if !ok {
			return nil
		}
		key := strings.TrimSuffix(p, "[]")
		cur = mm[key]
		if strings.HasSuffix(p, "[]") {
			a := arr(cur)
			if len(a) == 0 {
				return nil
			}
			cur = normDoc(a[0])
		}
	}
	return cur
}

func deepCopy(m M) M {
	b, _ := json.Marshal(m)
	var out M
	_ = json.Unmarshal(b, &out)
	return normNumbers(out).(M)
}

// diffPaths lists the dotted paths (array index → []) where a and b differ.
func diffPaths(a, b interface{}, prefix string, out map[string]bool) {
	am, aok := a.(M)
	bm, bok := b.(M)
	if aok && bok {
		keys := map[string]bool{}
		for k := range am {
			keys[k] = true
		}
		for k := range bm {
			keys[k] = true
		}
		for k := range keys {
			p := k
			if prefix != "" {
				p = prefix + "." + k
			}
			diffPaths(am[k], bm[k], p, out)
		}
		return
	}
	aa, aok := a.([]interface{})
	ba, bok := b.([]interface{})
	if aok && bok && len(aa) == len(ba) {
		for i := range aa {
			diffPaths(aa[i], ba[i], prefix+"[]", out)
		}
		return
	}
	ja, _ := json.Marshal(a)
	jb, _ := json.Marshal(b)
	if string(ja) != string(jb) {
		out[prefix] = true
	}
}

func mapResource(t *testing.T, c *Ctx, res *Resource, fields map[string]interface{}) ([]mapRow, string) {
	var specs []fieldSpec
	walkSpec(fields, "", &specs)
	lb, nb, note := unwrapLegacy(res.Backend)
	var rows []mapRow
	if lb == nil {
		coll := "?"
		if nb != nil {
			coll = nb.coll
		}
		kind := fmt.Sprintf("**New adapter collection** `%s` (%s DB) — no legacy equivalent; every field is stored as sent. %s", coll,
			map[bool]string{true: "main", false: "store"}[nb != nil && nb.org], note)
		for _, fs := range specs {
			cls, mp := "new", "`"+coll+"."+strings.ReplaceAll(fs.path, "[]", "[]")+"`"
			if serverOwned[strings.Split(fs.path, ".")[0]] {
				cls, mp = "server", "envelope / server-owned"
			}
			rows = append(rows, mapRow{fs.path, fs.typ, mp, cls})
		}
		return rows, kind
	}
	db := "store DB"
	if lb.inMain || lb.mainOrg {
		db = "main DB"
	}
	kind := fmt.Sprintf("**Legacy** %s — collection `%s` (%s). Writes go through the existing v1 handlers%s.", res.Legacy, lb.coll, db,
		map[bool]string{true: "", false: " (read-only resource)"}[lb.v1.create != nil || lb.v1.update != nil])
	var ops []string
	if lb.noDelete != "" {
		ops = append(ops, "DELETE → 409 unsupported_legacy: "+lb.noDelete)
	}
	if lb.noRestore != "" {
		ops = append(ops, "restore → 409: "+lb.noRestore)
	}
	if lb.noUpdate != "" {
		ops = append(ops, "PATCH/PUT of mapped fields → 409: "+lb.noUpdate)
	}
	if lb.adapterSoftDelete {
		ops = append(ops, "soft delete kept in `erp.del` (legacy delete is destructive; `?hard=1` calls it)")
	}
	if lb.readOnly {
		ops = append(ops, "read-only")
	}
	if note != "" {
		ops = append(ops, note)
	}
	if len(ops) > 0 {
		kind += "\n\n- " + strings.Join(ops, "\n- ")
	}
	storeHex, sample := sampleDoc(t, c, res, lb)
	var rec0 M
	x := newMapCtx(c, storeHex)
	if sample != nil {
		rec0 = deepCopy(lb.toC(x, sample))
	}
	for _, fs := range specs {
		top := strings.Split(strings.TrimSuffix(strings.Split(fs.path, ".")[0], "[]"), "[")[0]
		row := mapRow{path: fs.path, typ: fs.typ}
		switch {
		case fs.path == "storeId":
			row.class, row.mapping = "mapped", "`store_id` (also selects the store database `store_<id>`)"
		case fs.path == "roundingAuto":
			row.class, row.mapping = "mapped", "`erp.x.roundingAuto`; the adapter computes the rounding and sends it as explicit `rounding_amount` (`auto_rounding_amount` false)"
		case top == "zatca" && res.Path != "stores" && !(lb.known[top] && lb.hybrid[top]):
			row.class, row.mapping = "computed", "server-owned: legacy `zatca.*` / `uuid` / `hash` / `prev_hash` / `invoice_count_value` (existing ZATCA flow)"
		case serverOwned[top]:
			row.class = "server"
			row.mapping = map[string]string{"id": "`_id` (hex; client ids kept as alias `erp.cid`)", "version": "`erp.v` (else derived from `updated_at`)",
				"history": "`erp.h` (else synthesized from legacy audit fields)", "createdAt": "`created_at`", "updatedAt": "`updated_at`",
				"createdBy": "`created_by_name` / `erp.cb`", "updatedBy": "`updated_by_name`", "deleted": "`" + nz(lb.deletedKey, "erp.del") + "` (`erp.del` when the legacy delete is destructive)"}[top]
		case !lb.known[top]:
			if rec0 != nil && getPath(rec0, fs.path) != nil && !lb.hybrid[top] {
				row.class, row.mapping = "computed", "read-only, derived from the legacy document"
			} else {
				row.class, row.mapping = "new", "`erp.x."+fs.path+"` (adapter extras; round-trips, invisible to the old app)"
			}
		default:
			row.class, row.mapping = probeField(t, x, lb, sample, rec0, fs, top)
			if lb.hybrid[top] && row.class == "mapped" {
				row.mapping += " (+ full object kept in `erp.x." + top + "`)"
			}
		}
		rows = append(rows, row)
	}
	return rows, kind
}

func nz(a, b string) string {
	if a != "" {
		return a
	}
	return b
}

func probeField(t *testing.T, x *mapCtx, lb *legacyBackend, sample, rec0 M, fs fieldSpec, top string) (string, string) {
	if lb.toL == nil {
		if getPath(rec0, fs.path) != nil {
			return "computed", "read from legacy (read-only resource)"
		}
		return "computed", "read-only resource"
	}
	if sample == nil || rec0 == nil {
		return "mapped", "mapped (no sample document to probe)"
	}
	cur := getPath(rec0, concrete(fs.path))
	val, ok := probeValue(fs, cur)
	if !ok {
		return "mapped", "mapped (not probed)"
	}
	rec1 := deepCopy(rec0)
	if !setPath(rec1, concrete(fs.path), val) {
		return "mapped", "mapped (empty in sample, not probed)"
	}
	ch := map[string]bool{top: true}
	a, errA := lb.toL(x, deepCopy(rec0), sample, ch, false)
	bb, errB := lb.toL(x, rec1, sample, ch, false)
	if errA != nil || errB != nil {
		e := errB
		if e == nil {
			e = errA
		}
		msg := e.Error()
		if ae, ok := e.(*APIError); ok && len(ae.Fields) > 0 {
			var fsx []string
			for k, v := range ae.Fields {
				fsx = append(fsx, k+": "+v)
			}
			sort.Strings(fsx)
			msg = strings.Join(fsx, "; ")
		}
		return "mapped", "mapped, validated (probe rejected: " + strings.ReplaceAll(truncate(msg, 120), "|", "/") + ")"
	}
	diffs := map[string]bool{}
	diffPaths(normDoc(a), normDoc(bb), "", diffs)
	if len(diffs) == 0 {
		if cur != nil {
			return "computed", "read from legacy; not written by the adapter"
		}
		return "mapped", "accepted; no legacy effect for this value"
	}
	var ps []string
	for p := range diffs {
		ps = append(ps, "`"+p+"`")
	}
	sort.Strings(ps)
	if len(ps) > 6 {
		ps = append(ps[:6], "…")
	}
	return "mapped", strings.Join(ps, ", ")
}
