#!/bin/bash

EXTVER=$(jq -r '.version' ${FATOORA_HOME}/global.json)

java -Djdk.module.illegalAccess=deny -Djdk.sunec.disableNative=false -jar ${FATOORA_HOME}/zatca-einvoicing-sdk-${EXTVER}.jar --globalVersion $EXTVER $1 $2 $3 $4 $5 $6




