name: Build and Deploy Go Application to production

on:
  push:
    branches:
      - master
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23.0"

      # Step 3: Forcefully clean Go module cache
      - name: Forcefully Clean Go Module Cache
        run: |
          rm -rf ~/go/pkg/mod
          go clean -cache -modcache -i -r

      # Step 4: Clear GitHub Actions Cache
      - name: Clear GitHub Actions Cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ github.run_id }}

      # Step 5: Install dependencies and build
      - name: Install dependencies
        run: go mod tidy

      - name: Build Application
        run: go build -ldflags="-X 'main.version=${{ github.sha }}'" -o pos-rest

      # Step 6: Set up SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      # Step 7: Stop Service
      - name: Stop Service
        run: |
          ssh -v -i private_key ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} "sudo systemctl stop start-api"

      # Step 8: Copy build file to server
      - name: Copy build file to server
        run: |
          scp -v -i private_key -o StrictHostKeyChecking=no pos-rest ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }}:${{ secrets.AWS_GO_API_PROD_DEST_PATH}}

      # Step 9: Start service & Verify service status
      - name: Start service & Verify service status
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl start start-api
            sha256sum ${{secrets.AWS_GO_API_PROD_DEST_PATH}}/pos-rest
            sudo systemctl status start-api